### ISSUE TITLE
 ‘zmq_event_t’ undeclared 

### ISSUE THREAD

**Issue by nikhil003** [scemama/f77_zmq#2]
Hi,

I am trying to build fortran binding for ZMQ and I faced this error. It comes right at the bottom of f77_zmq.c file. I was wondering if you help me resolve this.

python create_f77_zmq_h.py zmq.h
===========================================
ZMQ_PTR set to 8 (for 64-bit architectures)
===========================================
gcc -fPIC  -O3 -fPIC -Wall -pedantic -g -c f77_zmq.c -o f77_zmq.o
f77_zmq.c:1:0: warning: -fPIC ignored for target (all code is position independent)
   /*
 ^
f77_zmq.c: In function ‘f77_zmq_event_new_’:
f77_zmq.c:378:25: error: ‘zmq_event_t’ undeclared (first use in this function)
   return malloc (sizeof(zmq_event_t));
                         ^
f77_zmq.c:378:25: note: each undeclared identifier is reported only once for each function it appears in
f77_zmq.c: At top level:
f77_zmq.c:382:29: error: unknown type name ‘zmq_event_t’
 int f77_zmq_event_destroy_ (zmq_event_t* *event)
                             ^
f77_zmq.c:391:27: error: unknown type name ‘zmq_event_t’
 int f77_zmq_event_event_ (zmq_event_t* *event)
                           ^
f77_zmq.c:396:31: error: unknown type name ‘zmq_event_t’
 int f77_zmq_event_set_event_ (zmq_event_t* *event, int* bitfield)
                               ^
f77_zmq.c:402:27: error: unknown type name ‘zmq_event_t’
 int f77_zmq_event_value_ (zmq_event_t* *event)
                           ^
f77_zmq.c:407:31: error: unknown type name ‘zmq_event_t’
 int f77_zmq_event_set_value_ (zmq_event_t* *event, int* value)
                               ^
f77_zmq.c: In function ‘f77_zmq_event_new_’:
f77_zmq.c:379:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:25: recipe for target 'f77_zmq.o' failed
make: *** [f77_zmq.o] Error 1

**Comment by scemama** [comment]
Hi,
It seems that they removed the `zmq_event_t` struct in version 4.1.2 of ZeroMQ.
If you take version 4.0.7, it will work.
Thanks for noticing!

**Comment by nikhil003** [comment]
Hi again,

I compiled zeromq-4.0.7 as you suggested, however it is still throwing the error. I presume it might need zeromq-3x or 2x

**Comment by nikhil003** [comment]
Hi,

I managed to solve the issue. I compiled 4.0.7 and then I tried to compile f77_zmq. I was using Cygwin on windows to do the compile and I managed to get the examples working. 

I had to modify the makefile so that the linking of libraries could be done, but now it is sorted and it is working. Thanks for providing the fortran binding for zmq.

**Comment by scemama** [comment]
Good!
Can you please tell me what you changed in the makefile so I can correct the problem?
Thanks
Anthony

**Comment by nikhil003** [comment]
I am not sure if it will happen on linux or mac machines....i just added one flag for libzmq and then it linked with the zmq libraries...i modified similar thing in the makefile for examples as well

LDFLAGS=-L/path/to/zeromq-4.0.7/lib -lzmq

libf77zmq.dll.a: f77_zmq.o
	$(CC) -shared $^ -o $@ $(LDFLAGS)

**Comment by scemama** [comment]
Thanks!

On 06/26/2015 09:16 AM, nikhil003 wrote:
>
> I am not sure if it will happen on linux or mac machines....i just
> added one flag for libzmq and then it linked with the zmq
> libraries...i modified similar thing in the makefile for examples as well
>
> LDFLAGS=-L/path/to/zeromq-4.0.7/lib -lzmq
>
> libf77zmq.dll.a: f77_zmq.o
> $(CC) -shared $^ -o $@ $(LDFLAGS)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scemama/f77_zmq/issues/2#issuecomment-115555575>.
>

-- 
Anthony Scemama
Laboratoire de Chimie et Physique Quantiques
IRSAMC - CNRS - Universite de Toulouse
