### ISSUE TITLE
f77_zmq_recv with allocatable string

### ISSUE THREAD

**Issue by nikhil003** [scemama/f77_zmq#3]
Hi,

I am trying to use the f77 bindings of zeromq together with json bindings for fortran. 

I was trying to use allocatable strings to receive messages from the localhost. I was wondering if it is possible. It seems like not possible at the moment. Is there any other way to use allocatable strings in f77_zmq_recv. 

I create a json file to string on server size, and then I created a client to get the string which can be parsed into json and array subsequently.

I have tried to see if the message is there using python and it is working if I make a client in python, but not when I try to do the same in fortran. I know that one of the argument in f77_zmq_recv is length of string.

I would appreciate any help or suggestion.

**Comment by scemama** [comment]
Hi,
It works with no problem. I changed the ``hwserver.f`` example with an allocatable string so that you can see how to do it. If you still have problems, post your code so that I can have a look.
Cheers,
Anthony

**Comment by nikhil003** [comment]
Hi,
So sorry for putting this up as an issue, I forgot to put allocate statement before using f77_zmq_recv command. Thanks for providing an example.
